version: '2'
services: 
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: ${AX_ID}-jaeger
    ports:
      - ${AX_JAEGER_UI_PORT}:16686
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778/tcp
    volumes:
      - ${AX_TZ_LOCAL}:/etc/localtime:ro
    networks:
      default:
        aliases:
          - jaeger.vm