version: '2'
services:  
  web:
    image: nginx:latest
    container_name: ${AX_ID}-web
    ports:
      - ${AX_WEB_PORT}:80
    volumes:
      - ${AX_TZ_LOCAL}:/etc/localtime:ro
      - ${AX_HOME}/sources:/var/www/html:rw
      - ${AX_HOME}/docker/web/log:/var/log/nginx
      - ${AX_HOME}/docker/web/nginx/dev.conf:/etc/nginx/conf.d/dev.conf
      - ${AX_HOME}/docker/web/nginx/origin.conf:/etc/nginx/conf.d/origin.conf
      - ${AX_HOME}/docker/web/nginx/site.conf:/etc/nginx/conf.d/site.conf
    networks:
      default:
        aliases:
          - web.vm
