
config:
	install -m 0755 -d $(CURDIR)/logs/server
	install -m 0755 -d $(CURDIR)/logs/manager
	touch $(CURDIR)/logs/supervisord.log

clean-config:

clean-data:
	rm -rf $(CURDIR)/log

clean-docker-rmi:
