version: '2'
services:
  mongo:
    image: mongo
    container_name: ${AX_ID}-mongo
    ports:
      - ${AX_MONGO_PORT}:27017
    volumes:
      - ${AX_TZ_LOCAL}:/etc/localtime:ro
      - ${AX_HOME}/docker/mongo/data:/data/db
    networks:
      default:
        aliases:
          - mongo.vm
