version: '2'
services:  
  php:
    build: 
      context: .
    image: ${AX_ID}_php
    container_name: ${AX_ID}-php
    volumes:
      - ${AX_TZ_LOCAL}:/etc/localtime:ro
      - ${AX_HOME}/sources:/var/www/html:rw
      - ${AX_HOME}/docker/php/ax.ini:/usr/local/etc/php/conf.d/ax.ini
      - ${AX_HOME}/docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ${AX_HOME}/docker/php/log/fpm-php.www.log:/var/log/fpm-php.www.log
    networks:
      default:
        aliases:
          - php.vm
